### ISSUE TITLE
Msc pacakges integration

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/sdmverse#9]
Based on the list used in Fig. 2:

- [x] demoniche
- [x] RangeShiftR
- [x] kuenm
- [x] ellipsenm
- [x] grinnel
- [x] sdm
- [x] usdm
- [x] ShinyBIOMOD
- [x] spThin
- [x] rangeModelMetadata
- [x] ecospat
- [x] blockCV
- [x] modEva
- [x] ENMeval
- [x] dismo
- [x] SSDM
- [x] biomod2
- [x] flexSDM
- [x] ENMTools
- [x] enmSdmX
- [x] ENMTML
- [x] fuzzySim
- [x] SDMtune
- [x] bam
- [x] KISSmig
- [x] embarcadero
- [x] NicheA
- [x] MinBAR
- [x] ntbox
- [x] Wallace
- [x] sampbias
- [x] CoordinateCleaner
- [x] bRacatus
- [x] occCite
- [x] rgbif
- [x] modleR

**Comment by sylvainschmitt** [comment]
ToDo: develop a wiki for submission with more infos. A step by step submission with R or online with GitHub. And list the common mistakes (use of "", use of :, spaces before :, removing the example file..., see #13 )

**Comment by hannahlowens** [comment]
> ToDo: develop a wiki for submission with more infos. A step by step submission with R or online with GitHub. And list the common mistakes (use of "", use of :, spaces before :, removing the example file..., see #13 )

Also add definitions of fields to the wiki?

**Comment by rvalavi** [comment]
Hi @sylvainschmitt the `blockCV` is missing from the list :)

**Comment by AMBarbosa** [comment]
`modEvA` is also missing from the above list

**Comment by sylvainschmitt** [comment]
@rvalavi & @AMBarbosa, sorry it was a quick list I made from the msc. It was just to have a aim of a minimum of packages to get. But in the end they are all welcome.

**Comment by rvalavi** [comment]
Oh no problem at all @sylvainschmitt! just highlighted the missing package :)
Thanks for the great work.

I couldn't add any reviewers to my pull request! Is there any permission restriction or something?

**Comment by sylvainschmitt** [comment]
> I couldn't add any reviewers to my pull request! Is there any permission restriction or something?

Please discuss your PR in #18
